databases:
  - name: flix
    databaseName: flix
    user: flix

services:
  - type: web
    name: flix
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flix
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
